force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Milestone__c/Project_Milestone__c.object-meta.xml
<CustomObject>
    <label>Project Milestone</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Milestone__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>To select a project on the milestone.</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Milestones</relationshipLabel>
    <relationshipName>Project_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_To_Do__c/Project_To_Do__c.object-meta.xml
<CustomObject>
    <label>Project To Do</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>To Do Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project To Dos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_To_Do__c/fields/Project_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Project_Milestone__c</fullName>
    <label>Project Milestone</label>
    <referenceTo>Project_Milestone__c</referenceTo>
    <relationshipLabel>Project To Dos</relationshipLabel>
    <relationshipName>Project_To_Dos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProjectToDoControllerTest.cls
@isTest
private class ProjectToDoControllerTest {

    @isTest
    static void myUnitTest() {
        Project__c prj =  TestFactory.createProject(true);
        Project_Milestone__c milestone = TestFactory.createMilestone(true,prj.Id);
        Project_To_Do__c toDo = TestFactory.createToDo(true,milestone.Id,'Not Started');
        System.Assert(ProjectToDoController.getTodoCount(milestone.Id)>0,'Count is not matching');
        System.Assert(!ProjectToDoController.getProjectToDoList(milestone.Id,0).isEmpty(),'List is empty');
        delete toDo;
        delete milestone;
        System.Assert(ProjectToDoController.getTodoCount(milestone.Id)==0,'Count is not matching');
        System.Assert(ProjectToDoController.getProjectToDoList(milestone.Id,0).isEmpty(),'List is not empty');
    }
}