force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Milestone__c/Project_Milestone__c.object-meta.xml
<CustomObject>
    <label>Project Milestone</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Milestone__c/fields/Complete__c.field-meta.xml
<CustomField>
    <fullName>Complete__c</fullName>
    <label>% Complete</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Project_Milestone__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>To select a project on the milestone.</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Milestones</relationshipLabel>
    <relationshipName>Project_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Milestone__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Project_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Project_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
        <default>true</default>
        <label>Not Started</label>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <description>These values are common for the status field on Project, Milestone and To Do object</description>
    <masterLabel>Project Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProjectMilestoneController.cls
/**
 * @Description: This class is used as a controller for the projectMilestone LWC.
 * @Created date : 
 * @Created By : 
 */
public with sharing class ProjectMilestoneController {

    /**
     * @Description: This method is used to get the count of Project Milestones.
     */
    @AuraEnabled(cacheable=true)
    public static Integer milestoneCount(Id projectId){
        try {
            return [SELECT COUNT() FROM Project_Milestone__c WHERE Project__c = :projectId WITH USER_MODE];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Project_Milestone__c> getProjectMilestoneList(Id projectId,Integer offset){
        try {
            System.debug(projectId+' '+offset);
            List<Project_Milestone__c> lstPrjMilestones = new List<Project_Milestone__c>();
            for(Project_Milestone__c prj:[SELECT Id, Name , Complete__c,  Project__c, Status__c
            FROM Project_Milestone__c
            WHERE Project__c = :projectId
            WITH USER_MODE ORDER BY CreatedDate DESC LIMIT 5 OFFSET:offset] ){
                prj.Complete__c = prj.Complete__c !=null ? prj.Complete__c/100 : prj.Complete__c;
                lstPrjMilestones.add(prj);
            }
            return lstPrjMilestones;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
}