force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Project_Milestone__c/Project_Milestone__c.object-meta.xml
<CustomObject>
    <label>Project Milestone</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Milestone__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>To select a project on the milestone.</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Milestones</relationshipLabel>
    <relationshipName>Project_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Milestone__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Project_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_To_Do__c/Project_To_Do__c.object-meta.xml
<CustomObject>
    <label>Project To Do</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>To Do Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project To Dos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_To_Do__c/fields/Project_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Project_Milestone__c</fullName>
    <label>Project Milestone</label>
    <referenceTo>Project_Milestone__c</referenceTo>
    <relationshipLabel>Project To Dos</relationshipLabel>
    <relationshipName>Project_To_Dos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Project_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
        <default>true</default>
        <label>Not Started</label>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <description>These values are common for the status field on Project, Milestone and To Do object</description>
    <masterLabel>Project Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestFactory.cls
/**
 * Test Factory: To assist with creating test records for test classes 
 * */
@isTest
public class TestFactory {

    /**
     * Create a Project__c record with default values
     */
    public static Project__c createProject(Boolean create) {
        Project__c proj = new Project__c();
        proj.Name = 'Test Project';
        proj.description__c = 'Project Description';
        if(create){
            insert proj;
        }
        return proj;
    }

    /**
     * Create a Project_Milestone__c record with default values
     */
    public static Project_Milestone__c createMilestone(Boolean create,Id projectId) {
        Project_Milestone__c milestone = new Project_Milestone__c();
        milestone.Name = 'Test Milestone';
        milestone.Due_Date__c = Date.today().addDays(10);
        milestone.Project__c = projectId;
        if(create){
            insert milestone;
        }
        return milestone;
    }

    /**
     * Create Project_To_Do__c record with default values
     */
    public static Project_To_Do__c createToDo(Boolean create,Id milestoneId,String status) {
        Project_To_Do__c todo = new Project_To_Do__c();
        todo.Name = 'Test ToDo';
        todo.Status__c = status;
        todo.Due_Date__c = Date.today().addDays(10);
        todo.Project_Milestone__c = milestoneId;
        if(create){
            insert todo;
        }
        return todo;
    }
}