force-app/main/default/objects/Project_Milestone__c/Project_Milestone__c.object-meta.xml
<CustomObject>
    <label>Project Milestone</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Milestone__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Project_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_To_Do__c/Project_To_Do__c.object-meta.xml
<CustomObject>
    <label>Project To Do</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>To Do Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project To Dos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_To_Do__c/fields/Project_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Project_Milestone__c</fullName>
    <label>Project Milestone</label>
    <referenceTo>Project_Milestone__c</referenceTo>
    <relationshipLabel>Project To Dos</relationshipLabel>
    <relationshipName>Project_To_Dos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Project_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
        <default>true</default>
        <label>Not Started</label>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <description>These values are common for the status field on Project, Milestone and To Do object</description>
    <masterLabel>Project Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProjectToDoController.cls
public with sharing class ProjectToDoController {

        /**
     * @Description: This method is used to get the count of Project Milestones.
     */
    @AuraEnabled(cacheable=true)
    public static Integer getTodoCount(Id milestoneId){
        return [SELECT COUNT() FROM Project_To_Do__c WHERE Project_Milestone__c = :milestoneId WITH USER_MODE];
    }
    
    /**
     * @Description: This method is used to get the project to do list.
     */
    @AuraEnabled(cacheable=true)
    public static List<Project_To_Do__c> getProjectToDoList(Id milestoneId,Integer offset){
        try {
            return [SELECT Id, Name, Project_Milestone__c, Status__c, Due_Date__c
                    FROM Project_To_Do__c
                    WHERE Project_Milestone__c = :milestoneId
                    WITH USER_MODE ORDER BY Createddate DESC LIMIT 5 OFFSET :offset];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}